import { NextApiRequest, NextApiResponse } from 'next';

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  const championshipsData = [
    {
      id: 21,
      title: 'ASRC Formula 1 2025',
      logo: '/img/asrc_f1_2025/logo.png',
      serverName: 'ASRC Formula 1 2025',
      serverPass: 'asrc',
      leagueJoinQr: '/img/asrc_f1_2025/qr.png',
      cars: [
        {
          "carNumber": 2,
          "firstName": "Nick",
          "lastName": "Stepanenko",
          "teamName": "Atlassian Williams Racing",
          "teamLogo": "/img/asrc_f1_2025/teams/wi.png",
          "carImage": "/img/asrc_f1_2025/cars/02.png",
          "flagImage": "/img/flags/nl.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 2,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 3,
          "firstName": "Eric",
          "lastName": "Kumadey",
          "teamName": "McLaren Formula 1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/mc.png",
          "carImage": "/img/asrc_f1_2025/cars/03.png",
          "flagImage": "/img/flags/it.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 4,
          "firstName": "William",
          "lastName": "Snowden",
          "teamName": "McLaren Formula 1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/mc.png",
          "carImage": "/img/asrc_f1_2025/cars/04.png",
          "flagImage": "/img/flags/uk.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 5,
          "firstName": "Vladislav",
          "lastName": "Zenkov",
          "teamName": "Mercedes-AMG Petronas F1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/me.png",
          "carImage": "/img/asrc_f1_2025/cars/05.png",
          "flagImage": "/img/flags/ru.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 2,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 1,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 6,
          "firstName": "Timon",
          "lastName": "Soovik",
          "teamName": "Mercedes-AMG Petronas F1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/me.png",
          "carImage": "/img/asrc_f1_2025/cars/06.png",
          "flagImage": "/img/flags/de.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 7,
          "firstName": "Antonis",
          "lastName": "Paparinopoulos",
          "teamName": "Scuderia Ferrari HP",
          "teamLogo": "/img/asrc_f1_2025/teams/fe.png",
          "carImage": "/img/asrc_f1_2025/cars/07.png",
          "flagImage": "/img/flags/gr.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 10,
          "firstName": "Élisée",
          "lastName": "Tape",
          "teamName": "Aston Martin Aramco F1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/am.png",
          "carImage": "/img/asrc_f1_2025/cars/10.png",
          "flagImage": "/img/flags/ca.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 11,
          "firstName": "Flavio",
          "lastName": "Zongoli",
          "teamName": "HG Esports BlueBolt Tigers",
          "teamLogo": "/img/asrc_f1_2025/teams/bt.png",
          "carImage": "/img/asrc_f1_2025/cars/11.png",
          "flagImage": "/img/flags/it.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 13,
          "firstName": "Davide",
          "lastName": "Zanini",
          "teamName": "Optiminal Valle",
          "teamLogo": "/img/asrc_f1_2025/teams/ov.png",
          "carImage": "/img/asrc_f1_2025/cars/13.png",
          "flagImage": "/img/flags/it.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 14,
          "firstName": "Jackson",
          "lastName": "Kavanagh",
          "teamName": "Visa Cash App Racing Bulls F1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/vc.png",
          "carImage": "/img/asrc_f1_2025/cars/14.png",
          "flagImage": "/img/flags/us.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 15,
          "firstName": "Alvin",
          "lastName": "Tran",
          "teamName": "McLaren Formula 1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/mc.png",
          "carImage": "/img/asrc_f1_2025/cars/15.png",
          "flagImage": "/img/flags/us.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 17,
          "firstName": "Carlos",
          "lastName": "Frau",
          "teamName": "Stake F1 Team Kick Sauber",
          "teamLogo": "/img/asrc_f1_2025/teams/sa.png",
          "carImage": "/img/asrc_f1_2025/cars/17.png",
          "flagImage": "/img/flags/es.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 18,
          "firstName": "Lorenzo",
          "lastName": "Cappellini",
          "teamName": "HG Esports BlueBolt Lions",
          "teamLogo": "/img/asrc_f1_2025/teams/bl.png",
          "carImage": "/img/asrc_f1_2025/cars/18.png",
          "flagImage": "/img/flags/it.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 19,
          "firstName": "Uroš",
          "lastName": "Kastelic",
          "teamName": "Scuderia Ferrari HP",
          "teamLogo": "/img/asrc_f1_2025/teams/fe.png",
          "carImage": "/img/asrc_f1_2025/cars/19.png",
          "flagImage": "/img/flags/si.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 28,
          "firstName": "Piotr",
          "lastName": "Wojdyło",
          "teamName": "Mantis Racing",
          "teamLogo": "/img/asrc_f1_2025/teams/ma.png",
          "carImage": "/img/asrc_f1_2025/cars/28.png",
          "flagImage": "/img/flags/pl.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 29,
          "firstName": "Paulo",
          "lastName": "Rodrigues",
          "teamName": "MoneyGram Haas F1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/ha.png",
          "carImage": "/img/asrc_f1_2025/cars/29.png",
          "flagImage": "/img/flags/pt.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 32,
          "firstName": "Arco",
          "lastName": "Hollestelle",
          "teamName": "Visa Cash App Racing Bulls F1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/vc.png",
          "carImage": "/img/asrc_f1_2025/cars/32.png",
          "flagImage": "/img/flags/nl.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 35,
          "firstName": "Yaroslav",
          "lastName": "Shelomanov",
          "teamName": "Atlassian Williams Racing",
          "teamLogo": "/img/asrc_f1_2025/teams/wi.png",
          "carImage": "/img/asrc_f1_2025/cars/35.png",
          "flagImage": "/img/flags/ru.svg",
          "penaltyPoints": {
            1: 0,
            2: 2,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 37,
          "firstName": "Tomasz",
          "lastName": "Grobelny",
          "teamName": "Mantis Racing",
          "teamLogo": "/img/asrc_f1_2025/teams/ma.png",
          "carImage": "/img/asrc_f1_2025/cars/37.png",
          "flagImage": "/img/flags/pl.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 42,
          "firstName": "Maxim",
          "lastName": "Zhuravlev",
          "teamName": "BWT Alpine F1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/al.png",
          "carImage": "/img/asrc_f1_2025/cars/42.png",
          "flagImage": "/img/flags/ru.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 47,
          "firstName": "Sergey",
          "lastName": "Sapozhnikov",
          "teamName": "Atlassian Williams Racing",
          "teamLogo": "/img/asrc_f1_2025/teams/wi.png",
          "carImage": "/img/asrc_f1_2025/cars/47.png",
          "flagImage": "/img/flags/ru.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 53,
          "firstName": "Pablo Lopez",
          "lastName": "Garcia",
          "teamName": "Stake F1 Team Kick Sauber",
          "teamLogo": "/img/asrc_f1_2025/teams/sa.png",
          "carImage": "/img/asrc_f1_2025/cars/53.png",
          "flagImage": "/img/flags/es.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 54,
          "firstName": "Robert",
          "lastName": "Ryś",
          "teamName": "IRG Team",
          "teamLogo": "/img/asrc_f1_2025/teams/ir.png",
          "carImage": "/img/asrc_f1_2025/cars/54.png",
          "flagImage": "/img/flags/pl.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 67,
          "firstName": "Alessio",
          "lastName": "Spinelli",
          "teamName": "HG Esports BlueBolt Lions",
          "teamLogo": "/img/asrc_f1_2025/teams/bl.png",
          "carImage": "/img/asrc_f1_2025/cars/67.png",
          "flagImage": "/img/flags/it.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 69,
          "firstName": "Dejan",
          "lastName": "Kovacic",
          "teamName": "MoneyGram Haas F1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/ha.png",
          "carImage": "/img/asrc_f1_2025/cars/69.png",
          "flagImage": "/img/flags/si.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 70,
          "firstName": "Juanma",
          "lastName": "Fuentes",
          "teamName": "Aston Martin Aramco F1 Team",
          "teamLogo": "/img/asrc_f1_2025/teams/am.png",
          "carImage": "/img/asrc_f1_2025/cars/70.png",
          "flagImage": "/img/flags/es.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 79,
          "firstName": "Jero",
          "lastName": "Calleja",
          "teamName": "Oracle Red Bull Racing",
          "teamLogo": "/img/asrc_f1_2025/teams/rb.png",
          "carImage": "/img/asrc_f1_2025/cars/33.png",
          "flagImage": "/img/flags/es.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 81,
          "firstName": "Andrzej",
          "lastName": "Kananowicz",
          "teamName": "IRG Team",
          "teamLogo": "/img/asrc_f1_2025/teams/ir.png",
          "carImage": "/img/asrc_f1_2025/cars/81.png",
          "flagImage": "/img/flags/pl.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
        {
          "carNumber": 96,
          "firstName": "Dàigoro",
          "lastName": "Staurenghi",
          "teamName": "HG Esports BlueBolt Tigers",
          "teamLogo": "/img/asrc_f1_2025/teams/bt.png",
          "carImage": "/img/asrc_f1_2025/cars/96.png",
          "flagImage": "/img/flags/it.svg",
          "penaltyPoints": {
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
          },
        },
      ],
      races: [
        {
          id: 297,
          name: 'Australian Grand Prix',
          round: 1,
          laps: 58,
          mins: 120,
          tyres: ["C3 Hard", "C4 Medium", "C5 Soft"],
          trackMap: '/img/tracks/maps/melbourne_gp_f1.avif',
          trackLogo: '/img/tracks/logos/melbourne.png',
          raceDateTime: '2025-05-11T19:00:00Z',
        },
        {
          id: 298,
          name: 'South African Grand Prix',
          round: 2,
          laps: 68,
          mins: 120,
          tyres: ["C1 Hard", "C2 Medium", "C3 Soft"],
          trackMap: '/img/tracks/maps/kyalami_gp_f1.avif',
          trackLogo: '/img/tracks/logos/kyalami.png',
          raceDateTime: '2025-05-18T19:00:00Z',
        },
        {
          id: 299,
          name: 'Emilia Romagna Grand Prix',
          round: 3,
          laps: 63,
          mins: 120,
          tyres: ["C4 Hard", "C5 Medium", "C6 Soft"],
          trackMap: '/img/tracks/maps/imola_gp_f1.avif',
          trackLogo: '/img/tracks/logos/imola.png',
          raceDateTime: '2025-06-08T19:00:00Z',
        },
        {
          id: 300,
          name: 'Turkish Grand Prix',
          round: 4,
          laps: 58,
          mins: 120,
          tyres: ["C2 Hard", "C3 Medium", "C4 Soft"],
          trackMap: '/img/tracks/maps/istanbul_gp_f1.avif',
          trackLogo: '/img/tracks/logos/istanbul.png',
          raceDateTime: '2025-06-22T19:00:00Z',
        },
        {
          id: 301,
          name: 'Canadian Grand Prix',
          round: 5,
          laps: 70,
          mins: 120,
          tyres: ["C4 Hard", "C5 Medium", "C6 Soft"],
          trackMap: '/img/tracks/maps/montreal_gp_f1.avif',
          trackLogo: '/img/tracks/logos/montreal.png',
          raceDateTime: '2025-06-29T19:00:00Z',
        },
        {
          id: 302,
          name: 'Austrian Grand Prix',
          round: 6,
          laps: 71,
          mins: 120,
          tyres: ["C3 Hard", "C4 Medium", "C5 Soft"],
          trackMap: '/img/tracks/maps/red_bull_ring_gp_f1.avif',
          trackLogo: '/img/tracks/logos/red_bull_ring.png',
          raceDateTime: '2025-07-13T19:00:00Z',
        },
        {
          id: 303,
          name: 'British Grand Prix',
          round: 7,
          laps: 52,
          mins: 120,
          tyres: ["C1 Hard", "C2 Medium", "C3 Soft"],
          trackMap: '/img/tracks/maps/silverstone_gp_f1.avif',
          trackLogo: '/img/tracks/logos/silverstone.png',
          raceDateTime: '2025-07-20T19:00:00Z',
        },
        {
          id: 304,
          name: 'Hungarian Grand Prix',
          round: 8,
          laps: 70,
          mins: 120,
          tyres: ["C4 Hard", "C5 Medium", "C6 Soft"],
          trackMap: '/img/tracks/maps/hungaroring_gp_f1.avif',
          trackLogo: '/img/tracks/logos/hungaroring.png',
          raceDateTime: '2025-07-27T19:00:00Z',
        },
        {
          id: 305,
          name: 'German Grand Prix',
          round: 9,
          laps: 67,
          mins: 120,
          tyres: ["C3 Hard", "C4 Medium", "C5 Soft"],
          trackMap: '/img/tracks/maps/hockenheim_gp_f1.avif',
          trackLogo: '/img/tracks/logos/hockenheim.png',
          raceDateTime: '2025-08-10T19:00:00Z',
        },
        {
          id: 306,
          name: 'Belgian Grand Prix',
          round: 10,
          laps: 44,
          mins: 120,
          tyres: ["C2 Hard", "C3 Medium", "C4 Soft"],
          trackMap: '/img/tracks/maps/spa_gp_f1.avif',
          trackLogo: '/img/tracks/logos/spa.png',
          raceDateTime: '2025-08-17T19:00:00Z',
        },
        {
          id: 307,
          name: 'Italian Grand Prix',
          round: 11,
          laps: 53,
          mins: 120,
          tyres: ["C3 Hard", "C4 Medium", "C5 Soft"],
          trackMap: '/img/tracks/maps/monza_gp_f1.avif',
          trackLogo: '/img/tracks/logos/monza.png',
          raceDateTime: '2025-09-07T19:00:00Z',
        },
        {
          id: 308,
          name: 'Japanese Grand Prix',
          round: 12,
          laps: 53,
          mins: 120,
          tyres: ["C1 Hard", "C2 Medium", "C3 Soft"],
          trackMap: '/img/tracks/maps/suzuka_gp_f1.avif',
          trackLogo: '/img/tracks/logos/suzuka.png',
          raceDateTime: '2025-09-14T19:00:00Z',
        },
        {
          id: 309,
          name: 'Saudi Arabian Grand Prix',
          round: 13,
          laps: 50,
          mins: 120,
          tyres: ["C3 Hard", "C4 Medium", "C5 Soft"],
          trackMap: '/img/tracks/maps/jeddah_gp_f1.avif',
          trackLogo: '/img/tracks/logos/jeddah.png',
          raceDateTime: '2025-09-21T19:00:00Z',
        },
        {
          id: 310,
          name: 'Brazilian Grand Prix',
          round: 14,
          laps: 71,
          mins: 120,
          tyres: ["C3 Hard", "C4 Medium", "C5 Soft"],
          trackMap: '/img/tracks/maps/interlagos_gp_f1.avif',
          trackLogo: '/img/tracks/logos/interlagos.png',
          raceDateTime: '2025-09-28T19:00:00Z',
        },
      ],
    },
  ];

  res.status(200).json(championshipsData);
}
